version: '3'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  redis:
    image: redis
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    